### ISSUE TITLE
Installation stuck 

### ISSUE THREAD

**Issue by eriksachse** [pmndrs/gltfjsx#100]
Hellooo,
I tried to use this tool, but it get's stuck on the installation.

`npx gltfjsx 4kpoly_1ktexture.gltf `

results in

```
Need to install the following packages:
  gltfjsx
Ok to proceed? (y) y
⸨   ░░░░░░░░░░░░░░░⸩ ⠋ idealTree:restore-cursor: sill placeDep ROOT restore-cursor@3.1.0 OK for: cli-cursor@3.1.0 want: ^3.1.0
```

**Comment by drcmda** [comment]
nothing i can do there, this is npm. could be an outage.

**Comment by gsimone** [comment]
If you are stuck for this, maybe try the online version at https://gltf.pmnd.rs/

**Comment by gsimone** [comment]
Please reopen if you find that the issue doesn't depend on a temporary npm problem or your network

**Comment by BevyJiang** [comment]
I am also stuck with the installation. I have also tried the link above. It doesn't work either. Any solution?

**Comment by jrafaaael** [comment]
Same here. I run these commands: 
```
npx gltfjsx empire.gltf
Need to install the following packages:
  gltfjsx
Ok to proceed? (y) y
[     .............] - idealTree:restore-cursor: sill placeDep ROOT restore-cursor@3.1.0 OK for: cli-cursor@3.1.0 want:
```

**Comment by focux** [comment]
Same here, I tried to run the command several times and it was always getting stuck in the same line that the other posted above.
