### ISSUE TITLE
"Need to install the following package: gltfjsx" when running npx.

### ISSUE THREAD

**Issue by ashleymvanduzer** [pmndrs/gltfjsx#103]
Whenever running npx gltfjsx filename.glb I am being asked to install gltfjsx, if I click y the download starts, then freezes at idealTree:restore-cursor: sill placeDep ROOT restore-cur.. any ideas as to what might be causing this?

**Comment by ashleymvanduzer** [comment]
i just installed with --legacy-peer-deps flag and ran the npx command again, and it works. However I thought the point of npx was to not have to install an npm package to use them..

**Comment by drcmda** [comment]
i dont know, i can use it with npx just fine. i think if anything freezes during an npm install it's probably a service outage on their part.

**Comment by ashleymvanduzer** [comment]
good to know. thanks for the heads up!
