### ISSUE TITLE
ARCanvas antialiasing not working in ios xrviewer

### ISSUE THREAD

**Issue by JakeJustLearning** [pmndrs/gltfjsx#110]
I am using XR viewer to test and develop react with WEBXR content. However all the objects are extremely pixelated. am I missing some sort of setting? I have set `gl={{antialias:true}}` in the ARCanvas component. 

is there a need to set the screen size?

**Comment by drcmda** [comment]
`<Canvas dpr={[1, 2]}` but that's unrelated to gltfjsx. its just pixelratio which defaults to 1.

**Comment by JakeJustLearning** [comment]
@drcmda  tried this, but it still doesn't seem to solve the problem. still having pretty bad pixelation which I don't get rebuilding the same thing in three/XR without react.
