### ISSUE TITLE
Change material reflectivity

### ISSUE THREAD

**Issue by LauraPiccolo** [pmndrs/gltfjsx#111]
Hi,
How can I change the material reflectivity of my model?
Putting material-color on my Mesh elements works to change the color, but material-reflectivity doesn't affect the object.

Sorry I am not super familiar with Three. Any help would be appreciated :)

**Comment by LauraPiccolo** [comment]
Okay I just understood that reflectivity is actually not a valid material property.
How can I achieve that then?

**Comment by drcmda** [comment]
material-roughness={1} // diffused
material-roughness={0} // reflective

better consult three docs, there are a lot of props that affect surfaces

**Comment by LauraPiccolo** [comment]
Thank you so much!
