### ISSUE TITLE
error converting model (possible bug)

### ISSUE THREAD

**Issue by jasan-s** [pmndrs/gltfjsx#118]
I download the **[Adam Head](https://gltf.sketchfab.com/models/adamHead.zip)** 3d model  `.gltf` 

I then used the following command `npx gltfjsx adamHead.gltf -T draco` to generate `.js` and transformed `.glb` file

The glb seems fine(viewed in blender), the issue seems with the generated JS. 

The issue: some of the models parts are not correctly positioned. (See attached image) 

<img width="584" alt="Screen Shot 2021-12-03 at 2 07 53 PM" src="https://user-images.githubusercontent.com/13863953/144679379-7ac0ea07-913f-4feb-bbc0-4ac34244553e.png">

am i doing something incorrectly?

**Comment by drcmda** [comment]
try a higher precision, it cuts floats off at 2 digits by default.

**Comment by jasan-s** [comment]
Thanks @drcmda  that fixed it :)
