### ISSUE TITLE
transformed draco glb file is still large (6MB)

### ISSUE THREAD

**Issue by jasan-s** [pmndrs/gltfjsx#120]
I used the following command `npx gltfjsx adamHead.gltf -T draco` 

I was hoping the transformed glb file be less then 1MB. however its approx.. 6MB. 
Should i have compressed the texture images using something like Tiny PNG ? or even cut the resolution of the texture files before running the gltfjsx command operation?

**Comment by drcmda** [comment]
yes, perhaps, sqoosh, whatever you deem best. that and blender. i try to get any model at least under 1mb. with the defaults it's not always possible.
