### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by jasan-s** [pmndrs/gltfjsx#121]
For This [Model](https://sketchfab.com/3d-models/scifi-girl-v01-96340701c2ed4d37851c7d9109eee9c0#download) downloaded in glTF format 

ran the following commnad `npx gltfjsx scene.gltf -T draco` and the resulting JS crashes with error:
`index.js:12 Uncaught Could not load scene-transformed.glb: Unexpected token < in JSON at position 0`

**Comment by Saahiljeet-Singh** [comment]
@jasan-s : How were you able to resolve this issue ?

**Comment by jasan-s** [comment]
Human error that was fixed. I was  attempting to import the 3d file from incorrect path.
