### ISSUE TITLE
Export JSX back to glTF

### ISSUE THREAD

**Issue by axeldelafosse** [pmndrs/gltfjsx#128]
Is it possible to export the JSX back to glTF?

**Comment by CodyJasonBennett** [comment]
Yes, I'd use something like three's [`GLTFExporter`](https://threejs.org/docs/#examples/en/exporters/GLTFExporter).

**Comment by axeldelafosse** [comment]
Thanks Cody!

**Comment by PaulLockett** [comment]
When I try to use GLTFEXporter all I get is this:
{
    "asset": {
        "version": "2.0",
        "generator": "THREE.GLTFExporter"
    },
    "scenes": [
        {
            "nodes": [],
            "name": "AuxScene"
        }
    ],
    "scene": 0
}

even though I have a whole scene with may meshes that are animated
