### ISSUE TITLE
gltfjsx command error.

### ISSUE THREAD

**Issue by Jules003** [pmndrs/gltfjsx#153]
Hello, the following error occurs when I run the `npx gtlfjsx model.gltf` command in a shell env and I'm a little confused. if anyone could point out what I'm doing wrong that would be amazing.

(node:6616) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 Parse
TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:5555:34)
    at node:internal/deps/undici/undici:5877:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by noti56** [comment]
have the same issue

**Comment by rodrigo-mahamud** [comment]
same issue

**Comment by LionstoneDevelopment** [comment]
Same issue! Have been stuck here for a couple hours. Help would be appreciated.

**Comment by willmadd** [comment]
There's a few issues with gltfjsx and node 18, could be worth downgrading node to v16 and seeing if that works

**Comment by minhbui27** [comment]
As willmadd suggested, I downgraded to Node v16 by
npm install -g n (the node version manager)
sudo npm cache clean -f
sudo n 16.16.0
use node -v to check the version
(dont forget to go back to your current node version)
then it worked!

**Comment by tjterry** [comment]
Downgrading to `Node v16.17.0` did the trick for me.

**Comment by satvikpendem** [comment]
Same here, looks like it doesn't work on >16 versions of Node

**Comment by drcmda** [comment]
i might have inadvertedly caused another node 18 issue by using squoosh in v6 🫠 node and that brute forced esm switch is such a mess right now. 

npx gltfjsx@5.0.4 ... will work

**Comment by fatemeRasolzade** [comment]
I use this to transform to mesh : https://gltf.pmnd.rs/
