### ISSUE TITLE
I keep getting this error SyntaxError: Missing semicolon

### ISSUE THREAD

**Issue by AmirHo3einJS** [pmndrs/gltfjsx#154]
Hello, When i run `npx gltfjsx myModel.glb -t` i keep getting the below error:

![image](https://user-images.githubusercontent.com/101206088/181583082-f20a6548-6949-4513-bbf2-1686133b6543.png)

I tried using it without any options but the result was the same, How can I fix this problem?

**Comment by drcmda** [comment]
could you try again?

**Comment by AmirHo3einJS** [comment]
> could you try again?

Thank u, It's fixed now.
