### ISSUE TITLE
Different result when using fbx models with primitive component and using gltfjsx

### ISSUE THREAD

**Issue by AmirHo3einJS** [pmndrs/gltfjsx#155]
Hello, I use gltfjsx to create a graph of my model and everything works fine, but when I load and put the model component in the canvas, the result is this:

The little circle is the race track and it has not been scaled:
![image](https://user-images.githubusercontent.com/101206088/181782163-3bc6d3ca-4179-42ac-b849-7189dfd7b2cc.png)

The result after scaling the group:
![image](https://user-images.githubusercontent.com/101206088/181783059-b7b5238a-9866-4ae0-b3ae-78efa9ac984a.png)

When I use primitive component with FBX loader:
![image](https://user-images.githubusercontent.com/101206088/181783302-9e21d09b-0ce9-4a8e-8670-438939259523.png)

As you can see my model hasn't been loaded correctly. I don't know what am I missing here. Could you help me load my model with gltfjsx like FBX loader?

**Comment by drcmda** [comment]
usually it's precision. the jsx plots out the numbers, position={[0.1, 0.2, etc, if the model is really small or really big one or two digits after the dot aren't enough. try --precision=6 and see if it gets better

**Comment by drcmda** [comment]
if it doesn't help could you please attach the glb, then i can fix it.

**Comment by AmirHo3einJS** [comment]
> usually it's precision. the jsx plots out the numbers, position={[0.1, 0.2, etc, if the model is really small or really big one or two digits after the dot aren't enough. try --precision=6 and see if it gets better

I did it with -p 15 and it got better. but it's the material now. Some meshes use more than one material but the gltfjsx applies only one to each mesh. How can i solve this?

**Comment by AmirHo3einJS** [comment]
> if it doesn't help could you please attach the glb, then i can fix it.

Here is the glb:

[tunnel.zip](https://github.com/pmndrs/gltfjsx/files/9222092/tunnel.zip)

**Comment by drcmda** [comment]
multi material is not supported by gltfjsx, had no idea that blender can export that, or that gltf supports it. probably easy to add though. which mesh has multiple materials, do you know that? so that i don't have to look for the needle in the haystack.

**Comment by AmirHo3einJS** [comment]
> multi material is not supported by gltfjsx, had no idea that blender can export that, or that gltf supports it. probably easy to add though. which mesh has multiple materials, do you know that?
> 
> edit, I tried to console.log out any mesh that has array materials, but it finds none.

So here is what I have found. look at this image from blender:

![image](https://user-images.githubusercontent.com/101206088/181875280-185fd0a5-5347-4f2f-ad89-2e0a6eed8ef4.png)

the banner object uses 3 materials. and now the code is like this:

![image](https://user-images.githubusercontent.com/101206088/181875321-1a940bf0-78d2-4021-8bdf-f853aa8e381d.png)

and this is the shape of the banner:

![image](https://user-images.githubusercontent.com/101206088/181875344-922bea7c-0866-4008-95ea-167a8426d3ae.png)

so that means gltfjsx converts each object with multi-material to a group of objects. but why this object hasn't been loaded correctly and it is all black? take a look:

![image](https://user-images.githubusercontent.com/101206088/181875411-047de384-77ce-41ef-a9b9-8cdf21ac244b.png)

**Comment by AmirHo3einJS** [comment]
I think I have found what the problem is. The problem is the metallic factor of the objects. How can I reduce the metallic factor for all of my objects? should I do it in blender or can I do it in my code?

**Comment by drcmda** [comment]
No, that’s just how the gltf is stored, it will create multiple meshes, so there’s no problem. I would fix materials, metalness etc, in blender.

**Comment by AmirHo3einJS** [comment]
> No, that’s just how the gltf is stored, it will create multiple meshes, so there’s no problem. I would fix materials, metalness etc, in blender.
> 
> in general, you see metallic objects in blender because it has an environment map ootb. Three doesn’t so it’s black. Just slap drei/environment into the scene and you’ll see them.
> 
> closing this, there’s no bug to be fixed.

thanks for your help

**Comment by AmirHo3einJS** [comment]
> No, that’s just how the gltf is stored, it will create multiple meshes, so there’s no problem. I would fix materials, metalness etc, in blender.
> 
> in general, you see metallic objects in blender because it has an environment map ootb. Three doesn’t so it’s black. Just slap drei/environment into the scene and you’ll see them.
> 
> closing this, there’s no bug to be fixed.

@drcmda I have a question. How can I add an environment map same as the blender that just lights up my objects? I don't want to use any hdr file, just an env map that lights up my objects.
