### ISSUE TITLE
Error with types in useGLTF hook

### ISSUE THREAD

**Issue by iskhakgoodmans** [pmndrs/gltfjsx#167]
- `three` version: 0.146.0
- `@react-three/fiber` version: 8.9.1
- `@react-three/drei` version: 9.43.3
- `node` version: v14.18.2
- `npm` version: 7.5.6

### Problem description:

After creating the `tsx` file from `glb` file using `gltfjsx` tool, there was an error with types in `useGTLF` hook.

<img width="959" alt="Снимок экрана 2022-11-24 в 15 06 56" src="https://user-images.githubusercontent.com/110387604/203771173-09e65f89-ff04-4bc7-a147-06842675a35d.png">

### Relevant code:

Here is an example of code in [codesandbox](https://codesandbox.io/s/react-three-rapier-sensors-forked-ndg4vq?file=/src/Camera.tsx:321-390) (sandbox based on [this](https://twitter.com/etthugo/status/1595149420055920641)).

**Comment by drcmda** [comment]
everything typescript i would need your help, im not good enough to get types right myself.

**Comment by mihirgupta0900** [comment]
@drcmda I looked into the types for fiber and drei, and we might need to add more generic types. Will take out some time and try to raise a PR. 

But for the time being, a patch could be using `as unkown` type coercion. Not ideal, but atleast types won't be broken when generating the file.

```tsx
const { nodes, materials, animations } = useGLTF("/path") as unknown as GLTFResult
```

**Comment by rafelis1997** [comment]
Actually I think this solution is better for this 
https://github.com/pmndrs/gltfjsx/issues/101#issuecomment-1363432531
does it solve your problem?

**Comment by CodyJasonBennett** [comment]
This is fixed in Drei since https://github.com/pmndrs/drei/releases/tag/v9.89.1.
