### ISSUE TITLE
Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

### ISSUE THREAD

**Issue by Aur71** [pmndrs/gltfjsx#168]
When i change it to  Scene.jsx the error disappeared but the model does not render.

**Comment by drcmda** [comment]
This is just your bundled, sind require *.jsx. As for loading, the glb needs to be inside public, practically all examples in Fiber docs went through gltfjsx, you can look up how it’s done there

**Comment by Aur71** [comment]
ty

**Comment by drcmda** [comment]
it returns *.jsx by default now
