### ISSUE TITLE
run: npx gltfjsx model.gltf

### ISSUE THREAD

**Issue by burnham** [pmndrs/gltfjsx#171]
Before asking I like to do some research but I have a question that I can't solve, according to the [pmndrs/gltfjsx](https://github.com/pmndrs/gltfjsx) github documentation info:

```
A typical use-case
First you run your model through gltfjsx. npx allows you to use npm packages without installing them.
```

I run the command `**npx gltfjsx shoe.gltf**` and it gives me the following error:

(node:12892) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 Parse
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Thanks in advance for the help.

Attach:
![image](https://user-images.githubusercontent.com/249632/206911678-c61cd21f-968b-413b-99cf-3dfbd9529c11.png)

**Comment by tyfiero** [comment]
I'm getting the same error

**Comment by bogyz123** [comment]
I have the same problem, found a fix?

**Comment by burnham** [comment]
Solution and is working for me:

`When using GLTFJSX, you may get the error,

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

At the time of writing this warning, the latest LTS version of Node.js and GLTFJSX are incompatible.

Only if you get this error, you can execute a version of GLTFJSX that contains the fix.

For example, instead of running,

npx gltfjsx ./public/models/shoe-draco.glb

run this,

npx ggozad/gltfjsx#fix-dependencies ./public/models/shoe-draco.glb

Remember to only try this if you are experiencing the problem. The actual fix to GLTFJSX should be merged soon.

Another option is to unistall your version of NodeJS and install the specific NodeJS 16.18 LTS instead.

Install packages for your operating system can be found at https://nodejs.org/download/release/v16.18.1/`


Source: https://sbcode.net/react-three-fiber/gltfjsx/


In case you need some help, just contact me.

**Comment by QAJOSEP** [comment]
It's work but obviously I need to change the path to my gltf model, thanks Burnham and ggozad

**Comment by ggozad** [comment]
No problem @QAJOSEP , it's a trivial fix requiring just an update if draco, see https://github.com/pmndrs/gltfjsx/pull/169
Hopefully it gets merged soon.

**Comment by Sean-Bradley** [comment]
GLTFJSX 6.0.1 has just been pushed, but I am still getting the `undici` problem.
Can someone else check.

I cleared npx cache to be sure
```
$ npx clear-npx-cache
Need to install the following packages:
  clear-npx-cache@1.0.1
Ok to proceed? (y) y
```

Then ran GLTFJSX as described in docs.
```
$ npx gltfjsx .\public\models\shoe-draco.glb
Need to install the following packages:
  gltfjsx@6.0.1
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@squoosh/lib@0.4.0',
npm WARN EBADENGINE   required: { node: ' ^12.5.0 || ^14.0.0 || ^16.0.0 ' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
(node:3036) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
```

Using the previous fix no longer works. It returns a 404 error.
`npx ggozad/gltfjsx#fix-dependencies ./public/models/shoe-draco.glb`

WIn 11
PowerShell 
npx 9.2.0
node 18.12.1

**Comment by Sean-Bradley** [comment]
Thanks for restoring. I thought it was too late and gone forever.

**Comment by Sean-Bradley** [comment]
> please let me know when you resolve your issue so I can remove it again.

@ggozad Thanks, I just forked your version, and its working ok for me. So you can delete yours if you ever need.

```
$ npx Sean-Bradley/gltfjsx#fix-dependencies .\public\shoe-draco.glb
(node:4580) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time                                                    
(Use `node --trace-warnings ...` to show where the warning was created)
group removed (empty)
group removed (empty)                                                                                                                                               
 Done:  Shoe-draco.js
```

**Comment by drcmda** [comment]
@ggozad what is the fix? how can it be repaired?

**Comment by drcmda** [comment]
ok so looks like don already published an alpha. could you try again with latest gltfjsx? it seems to work now.

**Comment by ggozad** [comment]
Can verify that it works for me on `v19.3.0`

**Comment by Sean-Bradley** [comment]
gltfjsx@6.0.5 works for me on 18.12.1
Excellent, It's a great tool. Especially the `--transform` option.

**Comment by 1kaiser** [comment]
https://github.com/pmndrs/gltfjsx/issues/207#issuecomment-1605890811
