### ISSUE TITLE
Could not load from http;//localhost://Model.glb 404 not Found

### ISSUE THREAD

**Issue by DynamicAdi** [pmndrs/gltfjsx#202]
I am getting this issue while using with latest next js vision! I have tried to use useLoader too but didn't helped My current path is in public folder but its not loading please help!!!!!

**Comment by drcmda** [comment]
this is just a wrong path. try /model.glb or ./model.glb or use the url bar in your browser to access the asset.

**Comment by DynamicAdi** [comment]
> 

okay! Thanks :) 
thanks for help

**Comment by 1kaiser** [comment]
https://github.com/pmndrs/gltfjsx/issues/207#issuecomment-1605890811
