### ISSUE TITLE
CLI.js shows 'read-pkg-up' error [ERR_MODULE_NOT_FOUND]

### ISSUE THREAD

**Issue by kartik1601** [pmndrs/gltfjsx#219]
This error happens when I try to run the ```npx``` command to convert the gltf file into jsx. My current node version is ```v20.5.1``` and npm version is ```9.8.1```. I have also installed gltfjsx package to my node modules.

![image](https://github.com/pmndrs/gltfjsx/assets/98540770/b61b291a-530d-42e0-84b0-40082f2b0835)

**Comment by Enloch** [comment]
I got the same error as OP. It showed out of the blue as last week I was doing conversions fine.
![Code_aw4QvR8xYe](https://github.com/pmndrs/gltfjsx/assets/47111207/49430a73-40e2-4979-a3ee-150b5462e65d)

**Comment by kartik1601** [comment]
It's because the package.json file is missing the ```'read-pkg-up'``` attribute. Please fix that @bjornstar @Enloch @fortinmike @ggozad

**Comment by Alexp120** [comment]
same here, is there a way I can manually fix the dependency error or switch to an earlier version?      thought it was just because I'm a noob and did something wrong.

**Comment by nathaponb** [comment]
Switch to node 16 _(16.20.2)_
install gltfjsx globally `npm install -g gltfjsx`
gltfjsx ./model.gltf -t

**Comment by TymonZ** [comment]
I have the same issue

**Comment by kartik1601** [comment]
@nathaponb I've already tried this, it throws the same error. I've used node v16, v18 and v20, it doesn't work on any. Even after changing some packages.

**Comment by MatiasMontoto** [comment]
Have you tried running `npm install read-pkg-up` in your node_modules parent  directory (srdtu-revamp for you)? 
I had the same issue, and I solved it that way.

**Comment by nathaponb** [comment]
have you tried running the standalone `gltfjsx` cli without `npx` ?

**Comment by CarlosHenriqueMkt** [comment]
I mixed @nathaponb + @MatiasMontoto  and https://github.com/pmndrs/gltfjsx/issues/201#issuecomment-1568870629 to solve. The result is:   
  
  "dependencies": {
    "gltfjsx": "^6.2.11",
    "read-pkg-up": "^10.0.0",
    "sharp": "^0.32.5",
    
   I didn't have success using NPM, so I used Yarn and worked :)

**Comment by CarlosHenriqueMkt** [comment]
I mixed @nathaponb + @MatiasMontoto and #201 (comment) to solve. The result is:

"dependencies": {
"gltfjsx": "^6.2.11",
"read-pkg-up": "^10.0.0",
"sharp": "^0.32.5",

I didn't have success using NPM, so I used Yarn and worked :)

**Comment by Alexp120** [comment]
my solution that worked for node v18.17.0 :

npm install read-pkg-up

that's it it works perfectly now.

**Comment by HarshDubey1011** [comment]
For me I have tried all the above methods nothing worked.

So I cloned  the repository locally and run the same command(npx gltfjsx modelname.glb) from the gltfjsx directory and it works. I successfully generated the modelname.jsx file.

**Comment by emilie-coder** [comment]
I got it to work with npm install read-pkg-up

**Comment by kingkwongsta** [comment]
> I mixed @nathaponb + @MatiasMontoto and #201 (comment) to solve. The result is:
> 
> "dependencies": { "gltfjsx": "^6.2.11", "read-pkg-up": "^10.0.0", "sharp": "^0.32.5",
> 
> I didn't have success using NPM, so I used Yarn and worked :)

Amazing! I have been stuck on this forever and it worked, thank you

I used npm to install those three packages

**Comment by stphn** [comment]
> I used npm to install those three packages. Also currently on node v19.6.1
> 
> `npm i gltfjsx read-pkg-up sharp`

That also did the trick for me using pnpm on node:  v18.16.0


Thank you

**Comment by johnvnel** [comment]
It did install, but I have this severity warning:

`S Command Injection - https://github.com/advisories/GHSA-926x-m6m5-3mmp
No fix available
node_modules/push-dir

1 high severity vulnerability

Some issues need review, and may require choosing
a different dependency.`

is that fine?

**Comment by resetmerlin** [comment]
yeap it also worked on me. 

npm i gltfjsx read-pkg-up sharp 

works pretty fine(react vite environment). But the question is why it works?
