### ISSUE TITLE
Propagating userData

### ISSUE THREAD

**Issue by rob-myers** [pmndrs/gltfjsx#30]
In Blender we can attach `Custom Properties` to meshes e.g.

<img width="257" alt="Screenshot 2020-08-22 at 18 44 01" src="https://user-images.githubusercontent.com/1658537/90962466-23885f80-e4a8-11ea-9d31-a93c26461350.png">

If the export option `Include > Custom Properties` is checked, the exported gltf has field `nodes.{meshIndex}.extras.Wall`.

Would you mind passing this information into the generated `jsx` using the `userData` prop?

---

I've at least got it working locally:

```ts
// GLTFLoader.js
const meshNodes = this.json.nodes
// ...
Object.assign(c.userData, meshNodes[meshIndex].extras || {})

// gltfjsx.js
if (obj.userData) result += `userData={${JSON.stringify(obj.userData)}} `
```

**Comment by drcmda** [comment]
its in
