### ISSUE TITLE
[BUG] --root  works not correctly

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [pmndrs/gltfjsx#43]
```
cd src/blender/export && npx @react-three/gltfjsx scene.gltf -r /models/
```

generate this:

![image](https://user-images.githubusercontent.com/69426460/95289054-8aa07e80-0872-11eb-9350-4f0268c9436d.png)

but must this:

![image](https://user-images.githubusercontent.com/69426460/95289139-b7549600-0872-11eb-9250-c44b5ba2e31b.png)

**Comment by Badrpas** [comment]
`-r` expects a directory which is served by web server so resulting GLTF-file URL is relative to provided value.

I guess you are looking for something similar to `webpack`'s `publicPath` option which, to my knowledge, is not implemented in `gltfjsx`

**Comment by MaxmaxmaximusAWS** [comment]
@Badrpas we are talking about code generation, not a runtine
