### ISSUE TITLE
[BUG] Wrong call to useGLTF when using the --types flag

### ISSUE THREAD

**Issue by AndrewPrifer** [pmndrs/gltfjsx#48]
With the `--types` flag, gltfjsx generates code that calls `useGLTF` like this:
```ts
const { nodes, materials } = useGLTF<GLTFResult>('/stuff.gltf');
```
This is incorrect because `useGLTF` accepts 0 type arguments. The fix is either to modify `useGLTF` to accept a `GLTF`-compatible type argument, or to modify the call to the following:
```ts
const { nodes, materials } = useGLTF('/stuff.gltf') as GLTFResult;
```

**Comment by drcmda** [comment]
would you make a pr for this?

**Comment by AndrewPrifer** [comment]
@drcmda sure, for the second solution?

**Comment by drcmda** [comment]
i have no informed opinions about either, pick what you think is best for all.

**Comment by AndrewPrifer** [comment]
Alright, I like the second solution better, if there is a language feature for it, let's use it :)
