### ISSUE TITLE
Draco binary error: Objects are not valid as a React child

### ISSUE THREAD

**Issue by nathansearles** [pmndrs/gltfjsx#54]
**Error**

```
Objects are not valid as a React child (found: TypeError: e.DecoderBuffer is not a constructor). If you meant to render a collection of children, use an array instead.
```

**Versions**

- gltfjsx: 3.1.0
- Node: 14.15.1
- npm: 6.14.8
- npx: 6.14.8

**Reproduce**

1. Download draco model: https://github.com/pmndrs/gltfjsx/blob/master/example/public/scene_draco.glb
2. Run npx gltfjsx scene_draco.glb --draco
3. Note above error

Works as expect on non-draco models like: https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/Flamingo.glb

**Comment by nathansearles** [comment]
Could this have anything connection to [this issue](https://github.com/google/draco/issues/653) with the Draco decoders?

**Comment by drcmda** [comment]
Will look into it

**Comment by drcmda** [comment]
it's strange, i casnt reproduce it locally but once i do npx gltfjsx i get it ... :-S

**Comment by drcmda** [comment]
i hope its fixed
