### ISSUE TITLE
Wrap generated component in forwardRef

### ISSUE THREAD

**Issue by AndrewPrifer** [pmndrs/gltfjsx#55]
Would resolve this issue in particular: https://github.com/AndrewPrifer/react-three-editable/issues/49. @drcmda if there are no caveats to this, I could open a pull request, however I imagine to support cases when a ref is needed to the group inside the component as well, we would have to assume something like `react-merge-refs` being installed as a dependency.

**Comment by drcmda** [comment]
but cant users do that quickly by hand? i kind of dislike forwardref and how ugly it makes components look - and it will be terminated next react major.

**Comment by AndrewPrifer** [comment]
Yes, so I heard and I'm looking forward to it! I also suggested the same there, just thought I'd check with you.
