### ISSUE TITLE
How to convert jsx back to glft ?

### ISSUE THREAD

**Issue by bhaskarSingh** [pmndrs/gltfjsx#61]
I have modified my gltf file converted to jsx and now want to convert it back to gltf? How can I do it ?

**Comment by drcmda** [comment]
the gltf lives along the jsx tree, it is never changed or touched in any way. and you still need it to be present when you load it. all that gltfjsx does is extract some data from it to build a virtual graph or tree.

**Comment by bhaskarSingh** [comment]
Ah! Got it.
