### ISSUE TITLE
Auto import tag correction for useAnimations

### ISSUE THREAD

**Issue by eraygundogmus** [pmndrs/gltfjsx#73]
İssue : 
Can't resolve useAnimations in '@react-three/drei/useAnimations'

Fixed: 

import { useAnimations } from '@react-three/drei/core/useAnimations'

**Comment by joshuaellis** [comment]
duplicate issue relating to this pr: https://github.com/pmndrs/gltfjsx/pull/65

**Comment by eraygundogmus** [comment]
Thanks, I did not notice it.
