### ISSUE TITLE
Tube Geometry is not animating

### ISSUE THREAD

**Issue by sourabpramanik** [pmndrs/gltfjsx#80]
This is my project https://github.com/sourabpramanik/trial and taking references from this video https://www.youtube.com/watch?v=2pUzJOfekVE&t=1025s but the lines connecting the two points are not dashed and not even animating. I am using same configuration but still it's not happening.
@drcmda

**Comment by drcmda** [comment]
please use the poimandres discord or react-three-fiber github discussions for help and trouble shooting. issues is only for gltfjsx related bugs.
