### ISSUE TITLE
Particle's positions shifted

### ISSUE THREAD

**Issue by Reine0017** [pmndrs/gltfjsx#86]
I tried running both the js file (created after running npx gltfjsx) and the original glb model in react and the particles on the js file one has the wrong positions. 

For the js one, I used 
`import Model from "./Donut.js"`

and for the glb one I used:
`function Model(props) {
  const { scene, materials } = useGLTF("donut.glb")
  return <primitive object={scene} />;
}`

![Screenshot from 2021-05-15 19-34-55](https://user-images.githubusercontent.com/26247692/118357360-b926ca80-b5b4-11eb-93f0-306cd37a0feb.png)
![Screenshot from 2021-05-15 19-35-27](https://user-images.githubusercontent.com/26247692/118357364-bb892480-b5b4-11eb-8315-6fae12359b02.png)

**Comment by drcmda** [comment]
could you try upping the precision a little? it cuts numbers off at two digits, depending on the models size that could be too little. if it still doesnt work you could upload the model and i take a look.

**Comment by Reine0017** [comment]
Oh right, my model size is pretty small. I'll try to see if I can scale it up, thanks for the advice! I'll close this for now :)

**Comment by drcmda** [comment]
I meant the precision argument in gltfjsx 🙂 s one models are too small for the defaults but when you give it more precision day 4 or 6 it should be ok

**Comment by Reine0017** [comment]
> I meant the precision argument in gltfjsx  s one models are too small for the defaults but when you give it more precision day 4 or 6 it should be ok

Hey @drcmda, thanks a lot for this :) It's working now!
