### ISSUE TITLE
Joint objects are not included in output

### ISSUE THREAD

**Issue by AlexanderProd** [pmndrs/gltfjsx#88]
I've got a rigged model which includes a lot of joint objects, unfortunately I've noticed that all the objects which are behind a joint are not visible in the scene. They become visible when I delete the joint. 

This is what my model looks like  
<img width="1153" alt="Bildschirmfoto 2021-05-19 um 14 34 58" src="https://user-images.githubusercontent.com/3080903/118813790-c7742f80-b8af-11eb-9c50-1d9a61ecc18e.png">

This is what the object tree looks like in Cinema 4D.

<img width="478" alt="Bildschirmfoto 2021-05-19 um 14 34 34" src="https://user-images.githubusercontent.com/3080903/118814165-1fab3180-b8b0-11eb-90c7-6355345d77ce.png">

The Child objects are regular Polygon objects.

<img width="442" alt="Bildschirmfoto 2021-05-19 um 14 46 57" src="https://user-images.githubusercontent.com/3080903/118815190-43bb4280-b8b1-11eb-87cd-104e7f61ed00.png">

This is what my model looks like in the browser when I load the generated JSX file. As you can see only the part which is not a child of a joint is visible.

<img width="855" alt="Bildschirmfoto 2021-05-19 um 14 44 42" src="https://user-images.githubusercontent.com/3080903/118814817-d6a7ad00-b8b0-11eb-8715-baee3e7f2335.png">

I'm not sure if theyre not even included in the generated JSX file or simply not shown in the browser. 

I'm wondering how I can fix this since I need the joints for an animation. 

I can upload the model as Cinema 4D, FBX, OBJ or GLTF file.

**Comment by drcmda** [comment]
try using 

```jsx
const { scene } = useGLTF(url)
return <primitive object={scene} />
```

and see if the model shows correctly. if not the error must be with the c4d import. if it does show i would be glad if i could get that model so i can run tests.

**Comment by AlexanderProd** [comment]
> try using
> 
> ```js
> const { scene } = useGLTF(url)
> return <primitive object={scene} />
> ```
> 
> and see if the model shows correctly. if not the error must be with the c4d import. if it does show i would be glad if i could get that model so i can run tests.

Thank you, when I import the model like this it does show indeed. 
<img width="442" alt="Bildschirmfoto 2021-05-19 um 15 23 43" src="https://user-images.githubusercontent.com/3080903/118820070-38b6e100-b8b6-11eb-8d02-6f8863ff6acc.png">

I've attached the model as FBX and the GLTF export from Cinema.
[ Model.zip](https://github.com/pmndrs/gltfjsx/files/6509053/Model.zip)

**Comment by drcmda** [comment]
just a precision issue, the model is tiny, so it cuts off digits.

```jsx
npx gltf-pipeline -i UR3e.gltf -o scene.glb --draco.compressionLevel=10
npx gltfjsx scene.glb -p=6   
```

(added draco here to shrink it, 4mb was quite big)

https://codesandbox.io/s/basic-demo-forked-dp92s?file=/src/App.js

**Comment by AlexanderProd** [comment]
@drcmda Thanks a lot! I spend two days trying to figure out whats wrong with my model. It works perfectly now, out of curiousity, what was the problem with the joints?

**Comment by drcmda** [comment]
As I said, precision. If you look over your code you'll see scale={0} so it practically hid them. It uses two digits after the point by default, so 0.00123 end up being 0. By increasing digits this goes away. I'd still rather increase the model in the modeling software though.
