### ISSUE TITLE
Errors. Screen shot them. I think it might be a webpack issue. not sure. 

### ISSUE THREAD

**Issue by lowellwashere2020** [pmndrs/gltfjsx#89]
Followed the starter example in the repo but with changed assets. 

I checked the one model with a gltf validator and it says it doesn't have errors. 
https://github.khronos.org/glTF-Validator/

got the model from here as well. 
https://market.pmnd.rs/model/helicopter

yet with or without this model. I get a series of errors and I have no clue what the issue is. 

**### Error screen shots**
<img width="575" alt="Screen Shot 2021-05-20 at 2 35 25 PM" src="https://user-images.githubusercontent.com/73625111/119038330-9f043800-b978-11eb-99aa-dde0a7e40e6c.png">
<img width="569" alt="Screen Shot 2021-05-20 at 2 35 41 PM" src="https://user-images.githubusercontent.com/73625111/119038370-a88da000-b978-11eb-823d-8618a2be245e.png">

**### package.json settings.**
**<img width="409" alt="Screen Shot 2021-05-20 at 2 37 09 PM" src="https://user-images.githubusercontent.com/73625111/119038545-dd015c00-b978-11eb-88e5-4fb462d56ef6.png">**

**### wepack.config.js**
<img width="528" alt="Screen Shot 2021-05-20 at 2 38 52 PM" src="https://user-images.githubusercontent.com/73625111/119038754-1a65e980-b979-11eb-8b25-3550049239b6.png">

**Comment by joshuaellis** [comment]
This isn't an issue with GLTFJSX see here: https://github.com/pmndrs/drei/issues/397#issuecomment-844265830
