### ISSUE TITLE
Remote assets

### ISSUE THREAD

**Issue by njm222** [pmndrs/gltfjsx#92]
I think there might be an issue with using `gltfjsx` for remote assets.

pmndrs/market is using gltfjsx and all the assets are being served from a cdn

A link to the issue: [https://github.com/pmndrs/market/issues/57](https://github.com/pmndrs/market/issues/57)

**Comment by drcmda** [comment]
this is not gltfjsx imo but the string thats handed to it

**Comment by drcmda** [comment]
should be fixed
