### ISSUE TITLE
[BUG?] Cannot read property 'split' of undefined when importing parse from gltfjsx

### ISSUE THREAD

**Issue by quacrobat** [pmndrs/gltfjsx#96]
What is causing this error?

https://codesandbox.io/s/boring-haibt-d3d2c?file=/src/Model.js

**Comment by drcmda** [comment]
i dont understand what youre trying to do there it makes no sense to me.

**Comment by quacrobat** [comment]
What I was trying to do isn't important I guess, I cleaned up the sandbox to show the bug.
I may be missing something, but I get an error thrown anytime it tries to `import { parse } from "@react-three/gltfjsx"; `
and before even trying to call parse on anything. https://codesandbox.io/s/boring-haibt-d3d2c?file=/src/index.js
